### ISSUE TITLE
I cant run the server

### ISSUE THREAD

**Issue by zx3777** [collabora/WhisperLive#106]
windows 10 py310

when i run：
from whisper_live.server import TranscriptionServer
server = TranscriptionServer()
server.run("0.0.0.0", 9090)

i got this:
PS A:\x\x> python server.py
Traceback (most recent call last):
  File "A:\x\x\server.py", line 3, in <module>
    server.run("0.0.0.0", 9090)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper_live\server.py", line 149, in run
    server.serve_forever()
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\sync\server.py", line 218, in serve_forever
    poller = select.poll()
AttributeError: module 'select' has no attribute 'poll'

**Comment by makaveli10** [comment]
Can you try upgrading the websockets package?

**Comment by zx3777** [comment]
> Can you try upgrading the websockets package?

upgrade ws solved, thank you
