### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by neoOpus** [collabora/WhisperLive#12]
Hi,

I would like to know if Windows will be supported, I tried with the actual files but I am not able to make it work…

Any hint on how to make it work would be welcome.

**Comment by makaveli10** [comment]
How are you running it?
Could you share the issue you are facing?

**Comment by neoOpus** [comment]
Hi,

Here is a an error log 

`utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
2023-07-11 00:47:19.1512514 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '620'. It is not used by any node and should be removed from the model.
2023-07-11 00:47:19.1610851 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '623'. It is not used by any node and should be removed from the model.
2023-07-11 00:47:19.1662140 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '625'. It is not used by any node and should be removed from the model.
2023-07-11 00:47:19.1723463 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '629'. It is not used by any node and should be removed from the model.
2023-07-11 00:47:19.1770892 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '628'. It is not used by any node and should be removed from the model.
2023-07-11 00:47:19.1824525 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '131'. It is not used by any node and should be removed from the model.
2023-07-11 00:47:19.1966522 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '134'. It is not used by any node and should be removed from the model.
2023-07-11 00:47:19.2070076 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '136'. It is not used by any node and should be removed from the model.
2023-07-11 00:47:19.2118599 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '140'. It is not used by any node and should be removed from the model.
2023-07-11 00:47:19.2154268 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '139'. It is not used by any node and should be removed from the model.`

**Comment by makaveli10** [comment]
I see two issues:
- Make sure pyaudio is working correctly(```audio backend part```)
- Check your cuda installation and make sure the torch cuda version matches your windows cuda or doesnt exceed it.
I have cuda 11.2 and I am using ```torch==1.10.1+cu111```

**Comment by zoq** [comment]
Are you running Windows 11 or Windows 10?

**Comment by haobo724** [comment]
maybe not support torch  2.0.1+cu118?
here is the bug log 

& C:/Users/94836/miniconda3/envs/dl/python.exe c:/Study/PythonApp/wisper-live/main.py
Downloading: "https://github.com/snakers4/silero-vad/zipball/master" to C:\Users\94836/.cache\torch\hub\master.zip
C:\Users\94836\miniconda3\envs\dl\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Traceback (most recent call last):
  File "c:\Study\PythonApp\wisper-live\main.py", line 4, in <module>
    server = TranscriptionServer()
  File "C:\Users\94836\miniconda3\envs\dl\lib\site-packages\whisper_live\server.py", line 32, in __init__
    self.vad_model, _ = torch.hub.load(repo_or_dir='snakers4/silero-vad',
  File "C:\Users\94836\miniconda3\envs\dl\lib\site-packages\torch\hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\94836\miniconda3\envs\dl\lib\site-packages\torch\hub.py", line 587, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\94836/.cache\torch\hub\snakers4_silero-vad_master\hubconf.py", line 44, in silero_vad
    model = OnnxWrapper(os.path.join(model_dir, 'silero_vad.onnx'), force_onnx_cpu)
  File "C:\Users\94836/.cache\torch\hub\snakers4_silero-vad_master\utils_vad.py", line 24, in __init__
    self.session = onnxruntime.InferenceSession(path, sess_options=opts)
  File "C:\Users\94836\miniconda3\envs\dl\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__       
    raise e
  File "C:\Users\94836\miniconda3\envs\dl\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__       
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\94836\miniconda3\envs\dl\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by zoq** [comment]
Did you install `pip install soundfile` also, is this using the latest version, with the latest onnx fix - https://github.com/collabora/WhisperLive/commit/b5f9f1ed08c27c397fa984f37224bd2ec9af051b

**Comment by makaveli10** [comment]
@haobo724 for now you could do `python setup.py install` to install `whisper_live`
we will update the package on `pypi` by tomorrow.

**Comment by haobo724** [comment]
thank you for reply, I install it using python setup.py install command 
and now the console output like this 


Downloading VAD ONNX model...
Traceback (most recent call last):
  File "C:\Study\PythonApp\wisper-live\main.py", line 4, in <module>
    server = TranscriptionServer()
  File "C:\Users\94836\miniconda3\envs\dl\lib\site-packages\whisper_live-0.0.6-py3.9.egg\whisper_live\server.py", line 38, in __init__
  File "C:\Users\94836\miniconda3\envs\dl\lib\site-packages\whisper_live-0.0.6-py3.9.egg\whisper_live\vad.py", line 13, in __init__
  File "C:\Users\94836\miniconda3\envs\dl\lib\site-packages\whisper_live-0.0.6-py3.9.egg\whisper_live\vad.py", line 111, in download
  File "C:\Users\94836\miniconda3\envs\dl\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\94836\miniconda3\envs\dl\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\94836\miniconda3\envs\dl\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the specified file.

**Comment by zoq** [comment]
This seems VAD related, do you need the voice activity detection filter? Disabling it would be an easy workaround.

``FileNotFoundError: [WinError 2] The system cannot find the specified file.``

is not really helpful, can you tell us more about your system, so we can try to reproduce the issue?

**Comment by haobo724** [comment]
> This seems VAD related, do you need the voice activity detection filter? Disabling it would be an easy workaround.
> 
> `FileNotFoundError: [WinError 2] The system cannot find the specified file.`
> 
> is not really helpful, can you tell us more about your system, so we can try to reproduce the issue?

sure! 
my system is Windows 11 Pro ，using python 3.9

**Comment by zoq** [comment]
CPU only or do you have a GPU as well?

**Comment by haobo724** [comment]
> CPU only or do you have a GPU as well?

I have GPU as well, RTX 4070TI and pytorch 2.01+cuda 11.8

**Comment by zoq** [comment]
Thanks for the information, we are trying reproduce the issue on our side.

**Comment by zoq** [comment]
@haobo724 can you check the path mentioned here https://github.com/collabora/WhisperLive/blob/main/whisper_live/vad.py#L98 exists on your system? If not can you create a folder e.g. in your home directory and change the path in the file and test again?

**Comment by zoq** [comment]
Can you change it to an absolute path?

**Comment by zoq** [comment]
That is fine, perhaps you are running into a similar problem as solved in the PR https://github.com/collabora/WhisperLive/pull/53?

I tried to reproduce the issue on my side.

**Comment by haobo724** [comment]
> That is fine, perhaps you are running into a similar problem as solved in the PR #53?
> 
> I tried to reproduce the issue on my side.

thank you, that is the reason! finnally it works!
