### ISSUE TITLE
Attempting to run, experiencing import error

### ISSUE THREAD

**Issue by luquitared** [collabora/WhisperLive#170]
I am trying to run the backend on a debian linux server with A100 GPU.

After installing all pip packages and PyAudio, I try to run and get this error
``` bash
~/WhisperLive$ python run_server.py --port 9090                       --backend faster_whisper
Traceback (most recent call last):
  File "/home/lucasnegritto/WhisperLive/run_server.py", line 2, in <module>
    from whisper_live.server import TranscriptionServer
  File "/home/lucasnegritto/WhisperLive/whisper_live/server.py", line 12, in <module>
    from whisper_live.transcriber import WhisperModel
  File "/home/lucasnegritto/WhisperLive/whisper_live/transcriber.py", line 16, in <module>
    from faster_whisper.audio import decode_audio, pad_or_trim
ImportError: cannot import name 'pad_or_trim' from 'faster_whisper.audio' (/opt/conda/envs/whisper/lib/python3.12/site-packages/faster_whisper/audio.py)
```

I also tried docker, but it seems it halts on CUDA message:
``` bash
docker run -it --gpus all -p 9090:9090 ghcr.io/collabora/whisperlive-gpu:latest

==========
== CUDA ==
==========

CUDA Version 12.2.2

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
```

perhaps a specific version of python is required for the local version? looking for any ideas on how to break past these issues, thanks

**Comment by luquitared** [comment]
@kalradivyanshu thank you! this totally solved my problem
