### ISSUE TITLE
Server is not running - Linux ubuntu 22.04 problem in virtual Enviroment venv

### ISSUE THREAD

**Issue by mont13** [collabora/WhisperLive#231]
I found a problem with installation via venv on Linux Ubuntu 22.04.

After installing Python 3.10, I used setup.py from GitHub to install it in a virtual environment.

First, there is no path for libnccl.so.2. You have to add it manually, for example:

export LD_LIBRARY_PATH=/home/xxxx/Documents/python/whisperlive/lib/python3.10/site-packages/nvidia_nccl_cu12-2.20.5-py3.10-linux-x86_64.egg/nvidia/nccl/lib:$LD_LIBRARY_PATH

The second problem is the NumPy version. It is necessary to uninstall the old version with pip uninstall numpy and install a specific version, for example, pip install numpy==1.23.5.

These changes can be added to the script setup.py, for example.
After these changes, the server is running.

**Comment by meezlung** [comment]
I think you have to use `pip install whisper-live`. 

Though, I am still encountering the same **import and Attribute error with NumPy**. When I run `python run_server.py --port 9090 --backend faster_whisper`, the server fails to start because ONNX Runtime can’t import the NumPy C‑API:

## To Reproduce:
```
> py -3.11 -m venv .venv && . .venv./Scripts/activate
> pip install whisper-live
> python run_server.py --port 9090 --backend faster_whisper
```

## Error:
```
> python run_server.py --port 9090 --backend faster_whisper

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):
  File "run_server.py", line 40, in <module>
    from whisper_live.server import TranscriptionServer
  File "server.py", line 13, in <module>
    from whisper_live.vad import VoiceActivityDetector
  File "vad.py", line 5, in <module>
    import onnxruntime
  File "__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_server.py", line 40, in <module>
    from whisper_live.server import TranscriptionServer
  File "server.py", line 13, in <module>
    from whisper_live.vad import VoiceActivityDetector
  File "vad.py", line 5, in <module>
    import onnxruntime
  File "__init__.py", line 57, in <module>
    raise import_capi_exception
ImportError: _ARRAY_API not found
```

## Workaround:
I had to downgrade to `numpy<2.0` for the server to start successfully.
```
> pip uninstall -y numpy
> pip install "numpy<2.0"
```

## Suggestion:
The error suggests to change the `numpy` version in `setup.py` as shown below:
```
-    "numpy==1.26.4",
+    "numpy<2.0",
```
This approach would avoid pip installing NumPy 2.x.

## Source
https://stackoverflow.com/a/78636964

**Comment by makaveli10** [comment]
@meezlung the problem was in the setup.py file and not in requirements file which is now fixed here so we push the package to pypi with the correct numpy version
https://github.com/collabora/WhisperLive/blob/617f587699f2871d32383c981489da0fdad8bdd3/setup.py#L59
