### ISSUE TITLE
Simple Client Recording Attempt

### ISSUE THREAD

**Issue by justinlevi** [collabora/WhisperLive#39]
I start up the server via $ `python ./run_server.py`

```
(whisper_live)  whisperlive git:(main)✗  🚀 python ./run_server.py
Downloading: "https://github.com/snakers4/silero-vad/archive/master.zip" to /Users/justinwinter/.cache/torch/hub/master.zip
2023-08-21 12:14:34.119619 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer '628'. It is not used by any node and should be removed from the model.
2023-08-21 12:14:34.119647 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer '629'. It is not used by any node and should be removed from the model.
2023-08-21 12:14:34.119652 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer '623'. It is not used by any node and should be removed from the model.
2023-08-21 12:14:34.119655 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer '625'. It is not used by any node and should be removed from the model.
2023-08-21 12:14:34.119659 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer '620'. It is not used by any node and should be removed from the model.
2023-08-21 12:14:34.119696 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer '139'. It is not used by any node and should be removed from the model.
2023-08-21 12:14:34.119701 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer '131'. It is not used by any node and should be removed from the model.
2023-08-21 12:14:34.119704 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer '140'. It is not used by any node and should be removed from the model.
2023-08-21 12:14:34.119708 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer '134'. It is not used by any node and should be removed from the model.
2023-08-21 12:14:34.119711 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer '136'. It is not used by any node and should be removed from the model.
ERROR:root:no close frame received or sent
```

Then start up the client via: 

```
(whisper_live)  whisperlive git:(main)✗  🚀 python ./run_client.py
[INFO]: * recording
[INFO]: Waiting for server ready ...
False en transcribe
[INFO]: Opened connection
[INFO]: Server Ready!
Traceback (most recent call last):
  File "/Users/justinwinter/projects/whisperlive/./run_client.py", line 3, in <module>
    client()
  File "/Users/justinwinter/projects/whisperlive/whisper_live/client.py", line 298, in __call__
    self.client.record()
  File "/Users/justinwinter/projects/whisperlive/whisper_live/client.py", line 234, in record
    data = self.stream.read(self.CHUNK)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/whisper_live/lib/python3.9/site-packages/pyaudio/__init__.py", line 570, in read
    return pa.read_stream(self._stream, num_frames,
OSError: [Errno -9981] Input overflowed
```

// run_client.py

```
from whisper_live.client import TranscriptionClient
client = TranscriptionClient("0.0.0.0", "8080", is_multilingual=False, lang="en", translate=False)
client()
```

**Comment by zoq** [comment]
Are you running this on a mac?

**Comment by zoq** [comment]
A temporary workaround is to set `exception_on_overflow=False` in https://github.com/collabora/WhisperLive/blob/main/whisper_live/client.py#L234.

This might cause that we skip some frames, we are looking into updating the frame rate for the different platforms.

**Comment by justinlevi** [comment]
@zoq Thanks for the idea. Yes, I am on a mac. I tried setting the `exception_on_overflow=False` but still getting the same error:

```
(whisper_live)  whisperlive git:(main)✗  🚀 python ./run_client.py
[INFO]: * recording
[INFO]: Waiting for server ready ...
False en transcribe
[INFO]: Opened connection
[INFO]: Server Ready!
Traceback (most recent call last):
  File "/Users/justinwinter/projects/whisperlive/./run_client.py", line 3, in <module>
    client()
  File "/Users/justinwinter/projects/whisperlive/whisper_live/client.py", line 299, in __call__
    self.client.record()
  File "/Users/justinwinter/projects/whisperlive/whisper_live/client.py", line 235, in record
    data = self.stream.read(self.CHUNK)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/whisper_live/lib/python3.9/site-packages/pyaudio/__init__.py", line 570, in read
    return pa.read_stream(self._stream, num_frames,
OSError: [Errno -9981] Input overflowed
```

<img width="1096" alt="image" src="https://github.com/collabora/WhisperLive/assets/1117989/b288e5ed-7570-4066-b573-482463bf8dc5">


```

    def record(self, out_file="output_recording.wav"):
        n_audio_file = 0
        # create dir for saving audio chunks
        if not os.path.exists("chunks"):
            os.makedirs("chunks", exist_ok=True)
        try:
            for _ in range(0, int(self.RATE / self.CHUNK * self.RECORD_SECONDS)):
                if not Client.RECORDING: break
                self.exception_on_overflow=False
                data = self.stream.read(self.CHUNK)
                self.frames += data

                audio_array = Client.bytes_to_float_array(data)
                
                self.send_packet_to_server(audio_array.tobytes())

                # save frames if more than a minute
                if len(self.frames) > 60*self.RATE:
                    t = threading.Thread(
                        target=self.write_audio_frames_to_file,
                        args=(self.frames[:], f"chunks/{n_audio_file}.wav", )
                    )
                    t.start()
                    n_audio_file += 1
                    self.frames = b""
```

**Comment by zoq** [comment]
Okay, I can reproduce the issue on a mac, I'll come up with a fix.

**Comment by aavetis** [comment]
welp

**Comment by Geczy** [comment]
rip?

**Comment by zoq** [comment]
> welp

Do you still have this problem with the latest release?

**Comment by sbrnaderi** [comment]
I have pulled the latest changes from the git repo and I still have this issue on my mac. Have you made changes regarding this issue? 
Thanks.

**Comment by sbrnaderi** [comment]
OK, I just tried to increase the self.chuck value to 1024 * 4 and I don't get the error anymore and the transcription works fine.
This is in client.py file. 
<img width="956" alt="Screenshot 2023-11-18 at 12 56 03" src="https://github.com/collabora/WhisperLive/assets/10099951/4d42b943-d21a-42a3-b945-f25e6da577e1">

**Comment by zoq** [comment]
This is on a mac?

**Comment by sbrnaderi** [comment]
> This is on a mac?

Yes, this is on MacBook Pro (intel based). I increased the chunk size and I could get the code to work. I also noticed that if I use the bigger Whisper model (medium), then I have to increase this further to 1024 * 8.

**Comment by arbianqx** [comment]
This issue still persists on macbook. Tried sending an audio file, is working just fine.

**Comment by zoq** [comment]
Looking into it today.

**Comment by niderhoff** [comment]
> OK, I just tried to increase the self.chuck value to 1024 * 4 and I don't get the error anymore and the transcription works fine. This is in client.py file. <img alt="Screenshot 2023-11-18 at 12 56 03" width="956" src="https://private-user-images.githubusercontent.com/10099951/283997168-4d42b943-d21a-42a3-b945-f25e6da577e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDQ5NTksIm5iZiI6MTcwMjkwNDY1OSwicGF0aCI6Ii8xMDA5OTk1MS8yODM5OTcxNjgtNGQ0MmI5NDMtZDIxYS00MmEzLWI5NDUtZjI1ZTZkYTU3N2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEzMDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YmFjOTI2OTg5MzE0Y2QyN2E1MWQ2ZTFlOWE2ZDI2MWFjODljMWNmYjFmNDAxZjJiMmFkOGYxMDg2NjMzOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9MRAEDxISDS59SI3-cyEfeNAp2adu0rhmtfQMKpbaoM">

tried that but for me it still crashed with the original error.

**Comment by zoq** [comment]
I can confirm if I update the chunk  size it works. @niderhoff let try to figure out why it's not working on your system. Just to make sure our setup is the same. You are using the pip package, and not the docker container, or do you run the scripts without the pip package?

**Comment by asadal** [comment]
I have the same problem. 

```
[INFO]: * recording
[INFO]: Waiting for server ready ...
True ko transcribe
[INFO]: Opened connection
[INFO]: Server Ready!
Traceback (most recent call last):
  File "/Users/asadal/Documents/Dev/Hani/WhisperLive_streamlit.py", line 13, in <module>
    client()
  File "/Users/asadal/miniconda3/lib/python3.10/site-packages/whisper_live/client.py", line 490, in __call__
    self.client.record()
  File "/Users/asadal/miniconda3/lib/python3.10/site-packages/whisper_live/client.py", line 371, in record
    data = self.stream.read(self.chunk)
  File "/Users/asadal/miniconda3/lib/python3.10/site-packages/pyaudio/__init__.py", line 570, in read
    return pa.read_stream(self._stream, num_frames,
OSError: [Errno -9981] Input overflowed
```

Macbook Pro 14 M1 Pro. Simple client Recording. 
I used pip package.

```
# Run the client
from whisper_live.client import TranscriptionClient
client = TranscriptionClient(
  "localhost",
  9090,
  is_multilingual=True,
  lang="ko",
  translate=False,
  # model_size="small"
)
client()
```

Then, I encountered an error, 

TypeError: TranscriptionClient.__init__() got an unexpected keyword argument 'model_size'

So, I disabled the option, `model_size="small"` and ran again.
But an error occured, `OSError: [Errno -9981] Input overflowed`

I changed `self.chunk = 1024` to `self.chunk = 1024 * 4`. But encounterd same error.

**Comment by zoq** [comment]
We have to release the latest pip package, in the meantime you can remove `model_size="small"` from the `TranscriptionClient` call. For the overflow issue, can you try `stream.read(self.chunk, exception_on_overflow=False)` in https://github.com/collabora/WhisperLive/blob/main/whisper_live/client.py#L415

**Comment by asadal** [comment]
Thanks zoq,
I'll wait for update pip.
Thank you for creating such a great application.

Best Regards.

**Comment by makaveli10** [comment]
@asadal pip package is updated. Let us know if you are still facing the issue.

**Comment by kjyv** [comment]
I have had sucsess with the newest version and setting exception_on_overflow to False. Can this be set by default?

**Comment by zoq** [comment]
https://github.com/collabora/WhisperLive/pull/83 does that, we will merge it and release a new version

**Comment by makaveli10** [comment]
@JonathanLehner can you share more details when do you see the segfault?and does it happen always on the latest version?
