### ISSUE TITLE
Initial_prompt and vad_parameters not sent in first message

### ISSUE THREAD

**Issue by Khreas** [collabora/WhisperLive#95]
_This issue refers to changes introduced in the recent commit 72ead71, related to the addition of `vad_parameters` and `initial_prompt` parameters. I didn't see any branch related to it so I'm raising an issue instead of a comment_

Client requests seem to fail because of the lack of `initial_prompt` and `vad_parameter` keys in the first message. I reproduced this error with servers ran through either `run_server.py` or a Docker container.

Here are small snippets to reproduce the error:

* Server

```py
from whisper_live.server import TranscriptionServer

if __name__ == "__main__":
    server = TranscriptionServer()
    server.run("0.0.0.0", 9090)
```

* Client

```py
from whisper_live.client import TranscriptionClient

client = TranscriptionClient(
    "localhost",
    9090,
    is_multilingual=False,
    lang="en",
    translate=False,
    model_size="small",
)

client("tests/jfk.flac")
```

* Error obtained
```
 ERROR:websockets.server:connection handler failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/sync/server.py", line 499, in conn_handler
    handler(connection)
  File "/app/whisper_live/server.py", line 104, in recv_audio
    initial_prompt=options["initial_prompt"],
KeyError: 'initial_prompt'
```

I guess this comes from the lack of parameter forwarding in the `client.py` file during the opening of the websocket, which could be solved by this:

```py
    def on_open(self, ws):
        """
        Callback function called when the WebSocket connection is successfully opened.

        Sends an initial configuration message to the server, including client UID, multilingual mode,
        language selection, and task type.

        Args:
            ws (websocket.WebSocketApp): The WebSocket client instance.

        """
        print(self.multilingual, self.language, self.task)

        print("[INFO]: Opened connection")
        ws.send(
            json.dumps(
                {
                    "uid": self.uid,
                    "multilingual": self.multilingual,
                    "language": self.language,
                    "task": self.task,
                    "model_size": self.model_size,
                    "initial_prompt": self.initial_prompt, # added line
                    "vad_parameters": self.vad_parameters, # added line
                }
            )
        )
```

**Comment by makaveli10** [comment]
https://github.com/collabora/WhisperLive/pull/96
